# Generated by Django 5.0.6 on 2024-11-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_productimage_options_productimage_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["order", "id"]},
        ),
    ]
