# Generated by Django 5.0.6 on 2024-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_productimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="frontend_id",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
